#!/bin/bash

set -e

DB_PASSWORD="$1"

JWT_SECRET="$2"
RT_SECRET="$3"
QR_SECRET="$4"


cat << EOF

DATABASE_URL="postgres://postgres:$DB_PASSWORD@localhost:5432/tabibi_db"

JWT_SECRET=$JWT_SECRET
RT_SECRET=$RT_SECRET
QR_SECRET=$QR_SECRET

MAILERSEND_FROM="$MAILERSEND_FROM"
MAILERSEND_API_KEY="$MAILERSEND_API_KEY"

MAIL_HOST="$MAIL_HOST"
MAIL_PORT="$MAIL_PORT"
MAIL_USERNAME="$MAIL_USERNAME"
MAIL_PASSWORD="$MAIL_PASSWORD"
MAIL_ENCRYPTION="$MAIL_ENCRYPTION"
MAIL_FROM_ADDRESS="$MAIL_FROM_ADDRESS"
MAIL_FROM_NAME="$MAIL_FROM_NAME"


CLOUDINARY_NAME="$CLOUDINARY_NAME"
CLOUDINARY_API_KEY="$CLOUDINARY_API_KEY"
CLOUDINARY_API_SECRET="$CLOUDINARY_API_SECRET"

SENTRY_DNS="$SENTRY_DNS"

EOF
