/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createMedicineDTO {
  days: number;
  dosage: number;
  dosagePerDay?: string;
  gapInDays?: number;
  image?: string | null;
  name: string;
  startDatetime: string;
  subType:
    | 'normal_tablets'
    | 'lozenges_tablets'
    | 'sublingual_tablets'
    | 'syrups'
    | 'suspension'
    | 'gargle'
    | 'oral_ampoules'
    | 'IM'
    | 'IV'
    | 'SC'
    | 'ID'
    | 'eye_drops'
    | 'oral_drops'
    | 'ear_drops'
    | 'nasal_drops'
    | 'nasal_spray'
    | 'rectal'
    | 'vaginal'
    | 'creams'
    | 'ointments'
    | 'lotions'
    | 'local_sprays'
    | 'dermal_patches';
  type:
    | 'tablets'
    | 'capsules'
    | 'liquids'
    | 'injection'
    | 'drops'
    | 'effervescent'
    | 'inhalers'
    | 'suppositories'
    | 'topical'
    | 'vaginal_douches'
    | 'enema';
}
