/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createArticleDTO {
  data: {
    content: string;
    langCode: 'ar' | 'en';
    title: string;
  }[];
  image: string | null;
}
