/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export * from './createArticle.schema.js';
export * from './makeArticleHot.schema.js';
export * from './login.schema.js';
export * from './signup.schema.js';
export * from './verifyAccount.schema.js';
export * from './createContact.schema.js';
export * from './updateContact.schema.js';
export * from './createDisease.schema.js';
export * from './updateDisease.schema.js';
export * from './createMedicine.schema.js';
export * from './medicines.schema.js';
export * from './pauseAndResume.schema.js';
export * from './setTaken.schema.js';
export * from './updateUser.schema.js';
